Repository auth0/auth0-flutter, pull requests merged in 2023-04, with the labels that each got.

#235 Export `WebException` [SDK-4115]
  auth0_flutter/lib/auth0_flutter.dart
  auth0_flutter/lib/auth0_flutter_web.dart
Labels: check title

#236 Add note to `Credentials.refreshToken` [SDK-4116]
  auth0_flutter/lib/auth0_flutter_web.dart
  auth0_flutter_platform_interface/lib/src/credentials.dart
  auth0_flutter_platform_interface/lib/src/web/cache_location.dart
  auth0_flutter_platform_interface/lib/src/web/client_options.dart
Labels: check title

#237 Unexport `LogoutOptions`
  auth0_flutter/lib/auth0_flutter_web.dart
  auth0_flutter/lib/src/web/extensions/logout_options.extension.dart
  auth0_flutter/lib/src/web/js_interop.dart
Labels: review:tiny, check title

#240 [SDK-4121] fix: android unit test for isTooManyAttempts
  auth0_flutter/android/src/main/kotlin/com/auth0/auth0_flutter/AuthenticationExceptionExtensions.kt
  auth0_flutter/android/src/test/kotlin/com/auth0/auth0_flutter/AuthenticationExceptionExtensionsTest.kt
Labels: check title

#241 docs: clarify usage of redirectUrl and returnToUrl in docs
  auth0_flutter/lib/auth0_flutter_web.dart
Labels: check title

#243 Update FAQ to use markdown admonitions
  auth0_flutter/FAQ.md
Labels: documentation, check title

#245 Fix `flutter analyze` issues
  auth0_flutter/lib/src/web/auth0_flutter_plugin_real.dart
  auth0_flutter/test/web/auth0_flutter_web_test.dart
  auth0_flutter/test/web/jwt_decode_test.dart
  auth0_flutter/test/web/matchers/auth0_exception_matcher.dart
  auth0_flutter_platform_interface/lib/auth0_flutter_platform_interface.dart
  auth0_flutter_platform_interface/pubspec.yaml
Labels: check title

#250 Fix android unit tests on `main`
  auth0_flutter/android/src/main/kotlin/com/auth0/auth0_flutter/AuthenticationExceptionExtensions.kt
  auth0_flutter/android/src/test/kotlin/com/auth0/auth0_flutter/AuthenticationExceptionExtensionsTest.kt
Labels: ignore title check

#249 Document how to pass the port `3000` when running a web app
  auth0_flutter/README.md
  auth0_flutter/example/README.md
Labels: ignore title check

#251 Add support for requesting MFA challenges [SDK-4052]
  auth0_flutter/android/src/main/kotlin/com/auth0/auth0_flutter/Auth0FlutterPlugin.kt
  auth0_flutter/android/src/main/kotlin/com/auth0/auth0_flutter/request_handlers/api/MultifactorChallengeApiRequestHandler.kt
  auth0_flutter/android/src/test/kotlin/com/auth0/auth0_flutter/request_handlers/api/LoginWithOtpApiRequestHandlerTest.kt
  auth0_flutter/android/src/test/kotlin/com/auth0/auth0_flutter/request_handlers/api/MultifactorChallengeApiRequestHandlerTest.kt
  auth0_flutter/example/ios/Runner.xcodeproj/project.pbxproj
  auth0_flutter/example/ios/Tests/AuthAPI/AuthAPIHandlerTests.swift
  auth0_flutter/example/ios/Tests/AuthAPI/AuthAPILoginWithOTPMethodHandlerTests.swift
  auth0_flutter/example/ios/Tests/AuthAPI/AuthAPIMultifactorChallengeMethodHandlerTests.swift
  auth0_flutter/example/ios/Tests/AuthAPI/AuthAPISignupMethodHandlerTests.swift
  auth0_flutter/example/ios/Tests/AuthAPI/AuthAPISpies.swift
  auth0_flutter/example/ios/Tests/Utilities.swift
  auth0_flutter/ios/Classes/AuthAPI/AuthAPIHandler.swift
  auth0_flutter/ios/Classes/AuthAPI/AuthAPILoginWithOTPMethodHandler.swift
  auth0_flutter/ios/Classes/AuthAPI/AuthAPIMultifactorChallengeMethodHandler.swift
  auth0_flutter/ios/Classes/AuthAPI/AuthAPIUserInfoMethodHandler.swift
  auth0_flutter/lib/auth0_flutter.dart
  auth0_flutter/lib/src/authentication_api.dart
  auth0_flutter/pubspec.lock
  auth0_flutter/test/authentication_api_test.dart
  auth0_flutter/test/authentication_api_test.mocks.dart
  auth0_flutter/test/credentials_manager_test.mocks.dart
  auth0_flutter/test/web_authentication_test.mocks.dart
  auth0_flutter_platform_interface/lib/auth0_flutter_platform_interface.dart
  auth0_flutter_platform_interface/lib/src/auth/auth_multifactor_challenge_options.dart
  auth0_flutter_platform_interface/lib/src/auth/challenge.dart
  auth0_flutter_platform_interface/lib/src/auth/challenge_type.dart
  auth0_flutter_platform_interface/lib/src/auth0_flutter_auth_platform.dart
  auth0_flutter_platform_interface/lib/src/method_channel_auth0_flutter_auth.dart
  auth0_flutter_platform_interface/pubspec.lock
  auth0_flutter_platform_interface/test/method_channel_auth0_flutter_auth_test.dart
  auth0_flutter_platform_interface/test/method_channel_auth0_flutter_auth_test.mocks.dart
  auth0_flutter_platform_interface/test/method_channel_auth0_flutter_web_auth_test.mocks.dart
  auth0_flutter_platform_interface/test/method_channel_credentials_manager_test.mocks.dart
Labels: ignore title check

#254 Document how to load the SPA SDK in index.html
  auth0_flutter/README.md
Labels: documentation, review:tiny, ignore title check
