Repository auth0/auth0-flutter, pull requests merged in 2023-02, with the labels that each got.

#197 Add web platform boilerplate [SDK-3983]
  auth0_flutter/lib/auth0_flutter.dart
  auth0_flutter/lib/src/mobile/authentication_api.dart
  auth0_flutter/lib/src/mobile/credentials_manager.dart
  auth0_flutter/lib/src/mobile/web_authentication.dart
  auth0_flutter/lib/src/web.dart
  auth0_flutter/lib/src/web/auth0_flutter_plugin_real.dart
  auth0_flutter/lib/src/web/auth0_flutter_plugin_stub.dart
  auth0_flutter/lib/src/web/js_interop.dart
  auth0_flutter/pubspec.lock
  auth0_flutter/pubspec.yaml
  auth0_flutter_platform_interface/lib/auth0_flutter_platform_interface.dart
  auth0_flutter_platform_interface/lib/src/auth0_flutter_auth_platform.dart
  auth0_flutter_platform_interface/lib/src/auth0_flutter_web_auth_platform.dart
  auth0_flutter_platform_interface/lib/src/auth0_flutter_web_platform.dart
  auth0_flutter_platform_interface/pubspec.lock
Labels: check title

#198 af: [SDK-3958] Support SFSafariViewController
  auth0_flutter/FAQ.md
  auth0_flutter/example/ios/Flutter/AppFrameworkInfo.plist
  auth0_flutter/example/ios/Podfile
  auth0_flutter/example/ios/Runner.xcodeproj/project.pbxproj
  auth0_flutter/example/ios/Runner/AppDelegate.swift
  auth0_flutter/example/ios/Runner/Base.lproj/Main.storyboard
  auth0_flutter/example/ios/Runner/Info.plist
  auth0_flutter/example/ios/Tests/WebAuth/WebAuthLoginMethodHandlerTests.swift
  auth0_flutter/example/ios/Tests/WebAuth/WebAuthSpies.swift
  auth0_flutter/example/lib/example_app.dart
  auth0_flutter/ios/Classes/WebAuth/WebAuthExtensions.swift
  auth0_flutter/ios/Classes/WebAuth/WebAuthLoginMethodHandler.swift
  auth0_flutter/ios/Classes/WebAuth/WebAuthModels.swift
  auth0_flutter/lib/auth0_flutter.dart
  auth0_flutter/lib/src/web_authentication.dart
  auth0_flutter/pubspec.lock
  auth0_flutter/test/web_authentication_test.dart
  auth0_flutter_platform_interface/lib/auth0_flutter_platform_interface.dart
  auth0_flutter_platform_interface/lib/src/web-auth/safari_view_controller.dart
  auth0_flutter_platform_interface/lib/src/web-auth/web_auth_login_options.dart
  auth0_flutter_platform_interface/pubspec.lock
  auth0_flutter_platform_interface/test/method_channel_auth0_flutter_web_auth_test.dart
Labels: review:medium

#200 Release v1.1.0 (platform interface)
  auth0_flutter_platform_interface/CHANGELOG.md
Labels: check title

#201 Release 1.1.0 (bump version)
  auth0_flutter_platform_interface/pubspec.yaml
Labels: check title

#202 Release 1.1.0
  auth0_flutter/CHANGELOG.md
  auth0_flutter/ios/auth0_flutter.podspec
  auth0_flutter/lib/src/version.dart
  auth0_flutter/pubspec.lock
  auth0_flutter/pubspec.yaml
Labels: check title

#203 [SDK-3984] Support login on web platform
  auth0_flutter/example/lib/example_app.dart
  auth0_flutter/example/web/index.html
  auth0_flutter/lib/auth0_flutter.dart
  auth0_flutter/lib/auth0_flutter_web.dart
  auth0_flutter/lib/src/web/auth0_flutter_plugin_real.dart
  auth0_flutter/lib/src/web/auth0_flutter_plugin_stub.dart
  auth0_flutter/lib/src/web/js_interop.dart
  auth0_flutter_platform_interface/lib/auth0_flutter_platform_interface.dart
  auth0_flutter_platform_interface/lib/src/auth0_flutter_web_platform.dart
  auth0_flutter_platform_interface/lib/src/id_token_validation_config.dart
  auth0_flutter_platform_interface/lib/src/login_options.dart
  auth0_flutter_platform_interface/lib/src/web-auth/web_auth_login_options.dart
Labels: review:medium, check title

#207 Add `credentials()` and `hasValidCredentials()` [SDK-3997]
  auth0_flutter/example/lib/example_app.dart
  auth0_flutter/lib/auth0_flutter_web.dart
  auth0_flutter/lib/src/web/auth0_flutter_plugin_real.dart
  auth0_flutter/lib/src/web/auth0_flutter_plugin_stub.dart
  auth0_flutter/lib/src/web/credentials_extension.dart
  auth0_flutter/lib/src/web/js_interop.dart
  auth0_flutter/lib/src/web/jwt_decode.dart
  auth0_flutter/lib/src/web/jwt_decode_exception.dart
  auth0_flutter/lib/src/web/user_profile_extension.dart
  auth0_flutter_platform_interface/lib/src/auth0_flutter_web_platform.dart
Labels: review:large, check title

#208 Add JWT decoder tests
  auth0_flutter/test/web/jwt_decode_test.dart
  auth0_flutter_platform_interface/lib/auth0_flutter_platform_interface.dart
  auth0_flutter_platform_interface/lib/src/testing/auth0_exception_matcher.dart
Labels: review:small, check title

#209 Add tests for `CredentialsExtension.fromWeb()`
  .circleci/config.yml
  auth0_flutter/lib/src/utils/string_extension.dart
  auth0_flutter/lib/src/web/credentials_extension.dart
  auth0_flutter/test/web/credentials_extension_test.dart
  auth0_flutter/test/web/credentials_extension_test.html
Labels: review:small, check title
