Repository auth0/auth0-flutter, pull requests merged in 2023-07, with the labels that each got.

#288 Use M1 resource class for iOS CI tests
  .circleci/config.yml
Labels: review:small, ignore title check

#282 [SDK-3508] Fix Integration Test CI for Android
  .circleci/config.yml
  .gitignore
  appium-test/package-lock.json
  appium-test/package.json
  appium-test/test.js
  auth0_flutter/example/android/.gitignore
  auth0_flutter/example/android/app/build.gradle
  auth0_flutter/example/android/app/src/androidTest/kotlin/com/auth0/auth0_flutter_example/SmokeTest.kt
  auth0_flutter/example/android/gradlew
  auth0_flutter/example/android/gradlew.bat
  auth0_flutter/example/pubspec.yaml
Labels: ignore title check

#290 Add namespace to build.gradle
  auth0_flutter/android/build.gradle
  auth0_flutter/example/android/app/build.gradle
Labels: check title

#292 chore: Add `.semgrepignore` exclusions
  .semgrepignore
Labels: check title

#293 chore(security): Pin `pr-title-checker` to commit SHA
  .github/workflows/pr-title-checker.yml
Labels: check title
