Repository auth0/auth0-flutter, pull requests merged in 2023-06, with the labels that each got.

#272 fix: allow audience and scope to be supplied during initialization
  auth0_flutter/lib/auth0_flutter_web.dart
  auth0_flutter/lib/src/web/extensions/client_options_extensions.dart
  auth0_flutter/lib/src/web/js_interop.dart
  auth0_flutter_platform_interface/lib/src/web/client_options.dart
Labels: check title

#277 Mark the platform version field in the "Bug Report" issue form as not required
  .github/ISSUE_TEMPLATE/Bug Report.yml
Labels: review:tiny, ignore title check

#276 af: Pin Auth0.swift and its dependencies to last version that supports iOS 12
  auth0_flutter/ios/auth0_flutter.podspec
Labels: review:tiny

#278 Add automated publishing workflows [SDK-4044]
  .github/workflows/publish-af.yml
  .github/workflows/publish-afpi.yml
Labels: review:small, ignore title check
