Repository auth0/auth0-flutter, pull requests merged in 2023-03, with the labels that each got.

#210 Add tests for `UserProfileExtension.fromClaims()` [SDK-4004]
  auth0_flutter/lib/src/web/auth0_flutter_plugin_real.dart
  auth0_flutter/lib/src/web/extensions/credentials_extension.dart
  auth0_flutter/lib/src/web/extensions/string_extension.dart
  auth0_flutter/lib/src/web/extensions/user_profile_extension.dart
  auth0_flutter/lib/src/web/user_profile_extension.dart
  auth0_flutter/test/web/extensions/credentials_extension_test.dart
  auth0_flutter/test/web/extensions/credentials_extension_test.html
  auth0_flutter/test/web/extensions/user_profile_extension_test.dart
Labels: review:large, check title

#211 Support additional properties for SDK client
  auth0_flutter/lib/auth0_flutter.dart
  auth0_flutter/lib/auth0_flutter_web.dart
  auth0_flutter/lib/src/web/auth0_flutter_plugin_real.dart
  auth0_flutter/lib/src/web/auth0_flutter_plugin_stub.dart
  auth0_flutter/lib/src/web/extensions/client_options_extensions.dart
  auth0_flutter/lib/src/web/js_interop.dart
  auth0_flutter_platform_interface/lib/auth0_flutter_platform_interface.dart
  auth0_flutter_platform_interface/lib/src/auth0_flutter_web_platform.dart
  auth0_flutter_platform_interface/lib/src/web/cache_location.dart
  auth0_flutter_platform_interface/lib/src/web/client_options.dart
Labels: check title

#215 Update the README of the app-facing package to include web content [SDK-4007]
  auth0_flutter/README.md
Labels: documentation, check title

#213 Update the root README [SDK-4007]
  README.md
Labels: documentation, check title

#217 Update the EXAMPLES to include web content [SDK-4007]
  auth0_flutter/EXAMPLES.md
Labels: documentation, review:medium, check title

#220 Add unit tests for `credentials()` and `hasValidCredentials()` [SDK-4004]
  auth0_flutter/test/web/auth0_fluter_web_test.dart
Labels: review:small, check title

#221 Move mobile tests under `mobile` directory
  auth0_flutter/test/mobile/authentication_api_test.dart
  auth0_flutter/test/mobile/authentication_api_test.mocks.dart
  auth0_flutter/test/mobile/credentials_manager_test.dart
  auth0_flutter/test/mobile/credentials_manager_test.mocks.dart
  auth0_flutter/test/mobile/web_authentication_test.dart
  auth0_flutter/test/mobile/web_authentication_test.mocks.dart
Labels: review:tiny, check title

#222 Wrap `onLoad` call with `kIsWeb` check in example app
  auth0_flutter/example/lib/example_app.dart
Labels: review:tiny, check title

#219 Update the FAQ and README of app-facing library [SDK-4007]
  auth0_flutter/FAQ.md
  auth0_flutter/README.md
Labels: documentation, review:tiny, check title

#218 Update the example README to include web content [SDK-4007]
  auth0_flutter/example/README.md
Labels: documentation, review:small, check title

#224 [SDK-4002] Add support for loginWithPopup
  auth0_flutter/example/lib/example_app.dart
  auth0_flutter/lib/auth0_flutter_web.dart
  auth0_flutter/lib/src/web/auth0_flutter_plugin_real.dart
  auth0_flutter/lib/src/web/auth0_flutter_plugin_stub.dart
  auth0_flutter/lib/src/web/auth0_flutter_web_platform_proxy.dart
  auth0_flutter/lib/src/web/js_interop.dart
  auth0_flutter/test/web/auth0_fluter_web_test.dart
  auth0_flutter_platform_interface/lib/auth0_flutter_platform_interface.dart
  auth0_flutter_platform_interface/lib/src/auth0_flutter_web_platform.dart
  auth0_flutter_platform_interface/lib/src/web/popup_login_options.dart
Labels: check title

#229 Improve API docs [SDK-4105]
  auth0_flutter/lib/auth0_flutter_web.dart
  auth0_flutter/lib/src/mobile/authentication_api.dart
  auth0_flutter/lib/src/mobile/web_authentication.dart
  auth0_flutter_platform_interface/lib/src/id_token_validation_config.dart
  auth0_flutter_platform_interface/lib/src/web-auth/safari_view_controller.dart
  auth0_flutter_platform_interface/lib/src/web/cache_location.dart
  auth0_flutter_platform_interface/lib/src/web/client_options.dart
Labels: documentation, review:small, check title

#228 Add missing snippets to EXAMPLES.md
  README.md
  auth0_flutter/EXAMPLES.md
Labels: documentation, review:small, check title

#230 Document `loginWithPopup()` on the README of app-facing library [SDK-4106]
  auth0_flutter/README.md
Labels: documentation, review:small, check title

#227 [SDK-4046] WebException wrapper
  auth0_flutter/lib/src/web/auth0_flutter_plugin_real.dart
  auth0_flutter/lib/src/web/extensions/web_exception_extensions.dart
  auth0_flutter/test/web/auth0_flutter_web_test.dart
  auth0_flutter/test/web/extensions/web_exception_extension_test.dart
  auth0_flutter_platform_interface/lib/auth0_flutter_platform_interface.dart
  auth0_flutter_platform_interface/lib/src/web/web_exception.dart
Labels: check title

#232 [SDK-4110] Support options to `getTokenSilently`
  auth0_flutter/lib/auth0_flutter_web.dart
  auth0_flutter/lib/src/web/auth0_flutter_plugin_real.dart
  auth0_flutter/lib/src/web/auth0_flutter_plugin_stub.dart
  auth0_flutter/lib/src/web/extensions/credentials_options_extension.dart
  auth0_flutter/lib/src/web/js_interop.dart
  auth0_flutter/lib/src/web/js_interop_utils.dart
  auth0_flutter/test/web/auth0_flutter_web_test.dart
  auth0_flutter_platform_interface/lib/auth0_flutter_platform_interface.dart
  auth0_flutter_platform_interface/lib/src/auth0_flutter_web_platform.dart
  auth0_flutter_platform_interface/lib/src/web/cache_mode.dart
  auth0_flutter_platform_interface/lib/src/web/credentials_options.dart
Labels: review:medium, check title
